# Data Understanding

This notebook is the starting point for exploring the supply chain demand forecasting dataset.

In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print("Pandas Version :", pd.__version__)
print("NumPy Version  :", np.__version__)

Pandas Version : 3.0.3
NumPy Version  : 2.5.0

In [8]:
data_path = "../data/raw/enterprise_supply_chain_dataset_india_2023_2025.xlsx"
df = pd.read_excel(data_path)
df.head()

,date,customer_id,order_id,product_id,product_name,category,brand,warehouse_id,city,state,...,stockout_flag,inventory_turnover,delivery_time_days,return_quantity,shipping_cost,profit_margin,demand_trend,weather,payment_method,delivery_status
0,2024-06-22,CUST100000,ORD202300000,P1096,Lakme Beaut 16,Beauty,Lakme,WH010,Vijayawada,Andhra Pradesh,...,No,0.26,6,1,285.54,14.60,Stable,Cold,UPI,In Transit
1,2025-02-20,CUST100001,ORD202300001,P1077,Prestige Hom 17,Home,Prestige,WH008,Kochi,Kerala,...,No,0.11,3,2,74.58,-9.31,Stable,Cloudy,Net Banking,Delivered
2,2024-06-23,CUST100002,ORD202300002,P1065,Milton Hom 5,Home,Milton,WH003,Mumbai,Maharashtra,...,No,0.24,7,1,207.21,23.24,Decreasing,Sunny,Cash on Delivery,Delivered
3,2025-09-27,CUST100003,ORD202300003,P1003,Sony Electronic 3,Electronics,Sony,WH002,Bengaluru,Karnataka,...,No,0.29,5,1,79.80,23.77,Stable,Cold,Credit Card,Delivered
4,2025-12-16,CUST100004,ORD202300004,P1078,Prestige Hom 18,Home,Prestige,WH007,Ahmedabad,Gujarat,...,No,0.37,4,0,116.85,-20.41,Increasing,Rainy,UPI,Delayed

In [9]:
df.shape

(5000, 41)

In [10]:
df.columns

Index(['date', 'customer_id', 'order_id', 'product_id', 'product_name',
       'category', 'brand', 'warehouse_id', 'city', 'state', 'region',
       'supplier_id', 'selling_price', 'procurement_cost', 'discount_percent',
       'promotion', 'promotion_name', 'promotion_type', 'holiday_flag',
       'holiday_name', 'festival_flag', 'festival_name', 'weekend', 'month',
       'day_of_week', 'units_sold', 'inventory_level', 'reorder_point',
       'safety_stock', 'supplier_lead_time_days', 'lead_time_variability',
       'stockout_flag', 'inventory_turnover', 'delivery_time_days',
       'return_quantity', 'shipping_cost', 'profit_margin', 'demand_trend',
       'weather', 'payment_method', 'delivery_status'],
      dtype='str')

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 41 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   date                     5000 non-null   datetime64[us]
 1   customer_id              5000 non-null   str
 2   order_id                 5000 non-null   str
 3   product_id               5000 non-null   str
 4   product_name             5000 non-null   str
 5   category                 5000 non-null   str
 6   brand                    5000 non-null   str
 7   warehouse_id             5000 non-null   str
 8   city                     5000 non-null   str
 9   state                    5000 non-null   str
 10  region                   5000 non-null   str
 11  supplier_id              5000 non-null   str
 12  selling_price            5000 non-null   float64
 13  procurement_cost         5000 non-null   float64
 14  discount_percent         5000 non-null   int64
 15  promotion                5000 non-null   str
 16  promotion_name           5000 non-null   str
 17  promotion_type           4290 non-null   str
 18  holiday_flag             5000 non-null   str
 19  holiday_name             60 non-null     str
 20  festival_flag            5000 non-null   str
 21  festival_name            100 non-null    str
 22  weekend                  5000 non-null   str
 23  month                    5000 non-null   str
 24  day_of_week              5000 non-null   str
 25  units_sold               5000 non-null   int64
 26  inventory_level          5000 non-null   int64
 27  reorder_point            5000 non-null   int64
 28  safety_stock             5000 non-null   int64
 29  supplier_lead_time_days  5000 non-null   int64
 30  lead_time_variability    5000 non-null   str
 31  stockout_flag            5000 non-null   str
 32  inventory_turnover       5000 non-null   float64
 33  delivery_time_days       5000 non-null   int64
 34  return_quantity          5000 non-null   int64
 35  shipping_cost            5000 non-null   float64
 36  profit_margin            5000 non-null   float64
 37  demand_trend             5000 non-null   str
 38  weather                  5000 non-null   str
 39  payment_method           5000 non-null   str
 40  delivery_status          5000 non-null   str
dtypes: datetime64[us](1), float64(5), int64(8), str(27)
memory usage: 1.6 MB

In [12]:
df.describe()

,date,selling_price,procurement_cost,discount_percent,units_sold,inventory_level,reorder_point,safety_stock,supplier_lead_time_days,inventory_turnover,delivery_time_days,return_quantity,shipping_cost,profit_margin
count,5000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.000000,5000.00000,5000.000000,5000.000000
mean,2024-07-06 19:30:43.200000,19988.820920,16897.809668,20.005000,58.347600,159.103600,55.130200,35.060800,7.152000,0.418950,3.982600,1.50600,193.320456,13.486116
min,2023-01-01 00:00:00,123.600000,115.540000,0.000000,5.000000,8.000000,30.000000,20.000000,2.000000,0.030000,1.000000,0.00000,40.060000,-33.320000
25%,2023-10-08 00:00:00,9823.012500,8267.327500,10.000000,39.000000,109.000000,42.000000,27.000000,4.000000,0.260000,2.000000,0.00000,116.507500,2.807500
50%,2024-07-04 00:00:00,19597.100000,16590.720000,20.000000,58.000000,159.000000,55.000000,35.000000,7.000000,0.370000,4.000000,2.00000,192.280000,15.760000
75%,2025-04-12 00:00:00,29377.575000,25088.320000,30.000000,78.000000,209.000000,68.000000,43.000000,10.000000,0.540000,6.000000,3.00000,270.337500,26.080000
max,2025-12-31 00:00:00,49991.000000,39287.970000,40.000000,119.000000,305.000000,80.000000,50.000000,12.000000,1.000000,7.000000,3.00000,349.990000,45.000000
std,NaN,12057.052206,10037.429610,12.419977,23.187106,62.467397,14.760814,9.039151,3.147329,0.214261,2.015716,1.12295,89.600842,16.867683

In [13]:
df.isnull().sum()

date                          0
customer_id                   0
order_id                      0
product_id                    0
product_name                  0
category                      0
brand                         0
warehouse_id                  0
city                          0
state                         0
region                        0
supplier_id                   0
selling_price                 0
procurement_cost              0
discount_percent              0
promotion                     0
promotion_name                0
promotion_type              710
holiday_flag                  0
holiday_name               4940
festival_flag                 0
festival_name              4900
weekend                       0
month                         0
day_of_week                   0
units_sold                    0
inventory_level               0
reorder_point                 0
safety_stock                  0
supplier_lead_time_days       0
lead_time_variability         0
stockout_flag                 0
inventory_turnover            0
delivery_time_days            0
return_quantity               0
shipping_cost                 0
profit_margin                 0
demand_trend                  0
weather                       0
payment_method                0
delivery_status               0
dtype: int64

In [14]:
df.duplicated().sum()

np.int64(0)